service: aws-teamcity-lambda
frameworkVersion: '2'

package:
  exclude:
    - node_modules/**
    - .pytest_cache/**

provider:
  name: aws
  runtime: python3.7
  memorySize: 256
  stackName: ${self:service}-${self:provider.stage}
  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'
  role: arn:aws:iam::633233947399:role/LambdaDevelopmentRole
  environment: ${file(.env.yml):${self:provider.stage}}

functions:
  update-template-db:
    description: 'Update database in RDS for TeamCity.'
    handler: src/updateTemplate.handler
    role: arn:aws:iam::633233947399:role/LambdaDevelopmentRole
    events:
      - s3:
          bucket: github-actions-tests-reports
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${file(.env.yml):${self:provider.stage}.BUCKET_FOLDER_PATH}
          existing: true

plugins:
  - serverless-python-requirements
